DROP TABLE IF EXISTS "orders";

CREATE TABLE IF NOT EXISTS "orders" (
    "ID" BIGINT AUTO_INCREMENT PRIMARY KEY,
    "PRODUCT_ID" BIGINT NOT NULL,
    "QUANTITY" INT NOT NULL,
    "TOTAL" DOUBLE NOT NULL,
    "STATUS" VARCHAR(20) NOT NULL,

    CHECK ("QUANTITY" > 0),
    CHECK ("TOTAL" >= 0)
);

CREATE INDEX IF NOT EXISTS idx_orders_product_id ON "orders" ("PRODUCT_ID");
