DROP TABLE IF EXISTS "products";

CREATE TABLE IF NOT EXISTS "products" (
    "ID" BIGINT AUTO_INCREMENT PRIMARY KEY,
    "NAME" VARCHAR(120) NOT NULL,
    "PRICE" DOUBLE NOT NULL,
    "STOCK" INT NOT NULL,
    "ACTIVE" BOOLEAN NOT NULL
);

